platform :ios, '11.0'
use_frameworks!

project 'RxViewExt.xcodeproj'
workspace 'RxViewExt'

target 'RxViewExt_Example' do

  pod 'RxViewExt', :path => '../'

  target 'RxViewExt_Tests' do
    inherit! :search_paths

    pod 'Quick',  '1.2.0'
    pod 'Nimble', '7.0.2'
  end
end
